### ISSUE TITLE
Wrong type argument: yas--template, t

### ISSUE THREAD

**Issue by d9d6ka** [mohkale/consult-yasnippet#9]
Hello!

I've bumped into the problem. I've installed `consult-yasnippet` and bound it to a keybinding.
When I press it the consult minibuffer appears with snippet variants. But when I select any the following error appears

> Wrong type argument: yas--template, t

or in Messages buffer

> consult-yasnippet--expand-template: Wrong type argument: yas--template, t

`yasnippet` and `consult-yasnippet` are configured as follows

```elisp
(catch 'setup-quit
        (if
                (straight-use-package 'yasnippet)
                nil
            (throw 'setup-quit nil))
        (eval-after-load 'yasnippet
            #'(lambda nil
                  (progn
                      (define-key yas-minor-mode-map
                          [(tab)]
                          #'nil)
                      (define-key yas-minor-mode-map "	" #'nil))))
        (yas-global-mode 1))

(catch 'setup-quit
        (if
                (straight-use-package 'consult-yasnippet)
                nil
            (throw 'setup-quit nil))
        (global-set-key
         [f7]
         #'consult-yasnippet))
```

The code above is the result of macro expansion produced by setup.el which I use to configure emacs.

BTW, I use emacs 28.1 under Win10.

**Comment by mohkale** [comment]
Hi. Could you try enabling `M-x toggle-debug-on-error` and paste the stacktrace from this error.

**Comment by d9d6ka** [comment]
Snippets are from `yasnippet-snippets`

**Comment by mohkale** [comment]
@d9d6ka 

Looks like one of the snippets in your collection isn't a snippet. Could you evaluate and share the value of `(yas--all-templates (yas--get-snippet-tables))` in your Messages buffer.

**Comment by d9d6ka** [comment]
> (#s(yas--template "defun" "(defun ${1:fun} (${2:args})
>        $0
> )" "defun" nil nil "c:/Users/vadim/AppData/Roaming/.cache/emacs/straight/build/yasnippet-snippets/snippets/lisp-interaction-mode/defun" nil nil "defun" ((menu-item "defun" ... :keys "defun =>")) nil ...) #s(yas--template "ah" "(add-hook '${1:name}-hook ${2:'${3:function}})$0
> " "add-hook" nil nil "c:/Users/vadim/AppData/Roaming/.cache/emacs/straight/build/yasnippet-snippets/snippets/emacs-lisp-mode/add-hook" nil nil "add-hook" ((menu-item "add-hook" ... :keys "ah =>")) nil ...) #s(yas--template "a" "(and $0)" "and" nil nil "c:/Users/vadim/AppData/Roaming/.cache/emacs/straight/build/yasnippet-snippets/snippets/emacs-lisp-mode/and" nil nil "and" ((menu-item "and" ... :keys "a =>")) nil ...) #s(yas--template "aref" "(aref ${1:array} ${2:index})
> " "aref" nil nil "c:/Users/vadim/AppData/Roaming/.cache/emacs/straight/build/yasnippet-snippets/snippets/emacs-lisp-mode/aref" nil nil "aref" ((menu-item "aref" ... :keys "aref =>")) nil ...) #s(yas--template "aset" "(aset ${1:array} ${2:index} ${3:element})" "aset" nil nil "c:/Users/vadim/AppData/Roaming/.cache/emacs/straight/build/yasnippet-snippets/snippets/emacs-lisp-mode/aset" nil nil "aset" ((menu-item "aset" ... :keys "aset =>")) nil ...) #s(yas--template "assq" "(assq ${1:key} ${2:list})" "assq" nil nil "c:/Users/vadim/AppData/Roaming/.cache/emacs/straight/build/yasnippet-snippets/snippets/emacs-lisp-mode/assq" nil nil "assq" ((menu-item "assq" ... :keys "assq =>")) nil ...) #s(yas--template "autoload" "(autoload ${1:function} \"${2:filename}\"${3: \"docstring\"}${4: interactive}${5: type})" "autoload" nil nil "c:/Users/vadim/AppData/Roaming/.cache/emacs/straight/build/yasnippet-snippets/snippets/emacs-lisp-mode/autoload" nil nil "autoload" ((menu-item "autoload" ... :keys "autoload =>")) nil ...) #s(yas--template "bc" "(backward-char $0)" "backward-char" nil nil "c:/Users/vadim/AppData/Roaming/.cache/emacs/straight/build/yasnippet-snippets/snippets/emacs-lisp-mode/backward-char" nil nil "backward-char" ((menu-item "backward-char" ... :keys "bc =>")) nil ...) #s(yas--template "bol" "(beginning-of-line)" "beginning-of-line" nil nil "c:/Users/vadim/AppData/Roaming/.cache/emacs/straight/build/yasnippet-snippets/snippets/emacs-lisp-mode/beginning-of-line" nil nil "beginning-of-line" ((menu-item "beginning-of-line" ... :keys "bol =>")) nil ...) #s(yas--template "botap" "(bounds-of-thing-at-point $0)" "bounds-of-thing-at-point" nil nil "c:/Users/vadim/AppData/Roaming/.cache/emacs/straight/build/yasnippet-snippets/snippets/emacs-lisp-mode/bounds-of-thing-at-point" nil nil "bounds-of-thing-at-point" ((menu-item "bounds-of-thing-at-point" ... :keys "botap =>")) nil ...) #s(yas--template "bfn" "(buffer-file-name)" "buffer-file-name" nil nil "c:/Users/vadim/AppData/Roaming/.cache/emacs/straight/build/yasnippet-snippets/snippets/emacs-lisp-mode/buffer-file-name" nil nil "buffer-file-name" ((menu-item "buffer-file-name" ... :keys "bfn =>")) nil ...) #s(yas--template "bmp" "(buffer-modified-p $0)" "buffer-modified-p" nil nil "c:/Users/vadim/AppData/Roaming/.cache/emacs/straight/build/yasnippet-snippets/snippets/emacs-lisp-mode/buffer-modified-p" nil nil "buffer-modified-p" ((menu-item "buffer-modified-p" ... :keys "bmp =>")) nil ...) ...)

**Comment by mohkale** [comment]
Okay, that wasn't very helpful since it got truncated :-(.

Shot in the dark, tell me what this outputs?

```lisp
(cl-find-if
 (lambda (it)
   (eq (cdr it) t))
 (consult-yasnippet--candidates
  (yas--all-templates (yas--get-snippet-tables))))
```

**Comment by d9d6ka** [comment]
> Debugger entered--Lisp error: (void-function consult-yasnippet--candidates)
>   (consult-yasnippet--candidates (yas--all-templates (yas--get-snippet-tables)))
>   (cl-find-if #'(lambda (it) (eq (cdr it) t)) (consult-yasnippet--candidates (yas--all-templates (yas--get-snippet-tables))))
>   (progn (cl-find-if #'(lambda (it) (eq (cdr it) t)) (consult-yasnippet--candidates (yas--all-templates (yas--get-snippet-tables)))))
>   eval((progn (cl-find-if #'(lambda (it) (eq (cdr it) t)) (consult-yasnippet--candidates (yas--all-templates (yas--get-snippet-tables))))) t)
>   elisp--eval-last-sexp(nil)
>   eval-last-sexp(nil)
>   funcall-interactively(eval-last-sexp nil)
>   command-execute(eval-last-sexp)

**Comment by mohkale** [comment]
Are you on the latest release? Make sure and run again.

**Comment by d9d6ka** [comment]
Emacs version is "GNU Emacs 28.1 (build 52, x86_64-w64-mingw32) of 2022-04-04"
`consult-yasnippet` is installed via straight today.
`consult-yasnippet--candidates' is in the el file.
It seems I've just had to require `consult-yasnippet` in the scratch buffer.

I've entered this
```elisp
(require 'consult-yasnippet)
(require 'cl-seq)

(cl-find-if
 (lambda (it)
   (eq (cdr it) t))
 (consult-yasnippet--candidates
  (yas--all-templates (yas--get-snippet-tables))))
```
and got `nil`

**Comment by mohkale** [comment]
Could you `M-x find-library consult-yasnippet`, `M-x eval-buffer`, toggle-debug-on-error again, produce and then paste the stack trace from before. A lot of it was obfuscated because it was bytecompiled.

**Comment by d9d6ka** [comment]
Sorry for delay...

Initial error stack trace

> Debugger entered--Lisp error: (wrong-type-argument yas--template t)
>   signal(wrong-type-argument (yas--template t))
>   (or (progn (and (memq (type-of template) cl-struct-yas--template-tags) t)) (signal 'wrong-type-argument (list 'yas--template template)))
>   (progn (or (progn (and (memq (type-of template) cl-struct-yas--template-tags) t)) (signal 'wrong-type-argument (list 'yas--template template))) (aref template 2))
>   (yas-expand-snippet (progn (or (progn (and (memq (type-of template) cl-struct-yas--template-tags) t)) (signal 'wrong-type-argument (list 'yas--template template))) (aref template 2)) nil nil (progn (or (progn (and (memq (type-of template) cl-struct-yas--template-tags) t)) (signal 'wrong-type-argument (list 'yas--template template))) (aref template 5)))
>   (progn (fset 'completing-read-multiple vnew) (fset 'yas-completing-read vnew) (yas-expand-snippet (progn (or (progn (and (memq (type-of template) cl-struct-yas--template-tags) t)) (signal 'wrong-type-argument (list 'yas--template template))) (aref template 2)) nil nil (progn (or (progn (and (memq (type-of template) cl-struct-yas--template-tags) t)) (signal 'wrong-type-argument (list 'yas--template template))) (aref template 5))))
>   (unwind-protect (progn (fset 'completing-read-multiple vnew) (fset 'yas-completing-read vnew) (yas-expand-snippet (progn (or (progn (and (memq ... cl-struct-yas--template-tags) t)) (signal 'wrong-type-argument (list 'yas--template template))) (aref template 2)) nil nil (progn (or (progn (and (memq ... cl-struct-yas--template-tags) t)) (signal 'wrong-type-argument (list 'yas--template template))) (aref template 5)))) (fset 'completing-read-multiple old) (fset 'yas-completing-read old))
>   (let* ((vnew #'(lambda (&rest _args) "")) (vnew #'(lambda (&rest _args) "")) (old (symbol-function 'completing-read-multiple)) (old (symbol-function 'yas-completing-read))) (unwind-protect (progn (fset 'completing-read-multiple vnew) (fset 'yas-completing-read vnew) (yas-expand-snippet (progn (or (progn (and ... t)) (signal 'wrong-type-argument (list ... template))) (aref template 2)) nil nil (progn (or (progn (and ... t)) (signal 'wrong-type-argument (list ... template))) (aref template 5)))) (fset 'completing-read-multiple old) (fset 'yas-completing-read old)))
>   consult-yasnippet--expand-template(t (146 . 146) "")
>   (unwind-protect (consult-yasnippet--expand-template template region region-contents) (unwind-protect (mapc #'yas--commit-snippet (yas-active-snippets (point-min) (point-max))) (setcdr region (- (point-max) orig-offset))))
>   (progn (unwind-protect (consult-yasnippet--expand-template template region region-contents) (unwind-protect (mapc #'yas--commit-snippet (yas-active-snippets (point-min) (point-max))) (setcdr region (- (point-max) orig-offset)))) (redisplay))
>   (if (and template (not (eq action 'return))) (progn (unwind-protect (consult-yasnippet--expand-template template region region-contents) (unwind-protect (mapc #'yas--commit-snippet (yas-active-snippets (point-min) (point-max))) (setcdr region (- (point-max) orig-offset)))) (redisplay)))
>   (let ((yas-verbosity 0) (inhibit-redisplay t) (inhibit-read-only t) (orig-offset (- (point-max) (cdr region))) (yas-prompt-functions '(yas-no-prompt))) (delete-region (car region) (cdr region)) (goto-char (car region)) (setcar region (point)) (insert region-contents) (setcdr region (point)) (if (and template (not (eq action 'return))) (progn (unwind-protect (consult-yasnippet--expand-template template region region-contents) (unwind-protect (mapc #'yas--commit-snippet (yas-active-snippets (point-min) (point-max))) (setcdr region (- (point-max) orig-offset)))) (redisplay))))
>   (save-current-buffer (set-buffer buf) (let ((yas-verbosity 0) (inhibit-redisplay t) (inhibit-read-only t) (orig-offset (- (point-max) (cdr region))) (yas-prompt-functions '(yas-no-prompt))) (delete-region (car region) (cdr region)) (goto-char (car region)) (setcar region (point)) (insert region-contents) (setcdr region (point)) (if (and template (not (eq action 'return))) (progn (unwind-protect (consult-yasnippet--expand-template template region region-contents) (unwind-protect (mapc #'yas--commit-snippet (yas-active-snippets ... ...)) (setcdr region (- ... orig-offset)))) (redisplay)))))
>   (closure ((region-contents . "") (region 146 . 146) (buf . #<buffer *scratch*>) t) (action template) (save-current-buffer (set-buffer buf) (let ((yas-verbosity 0) (inhibit-redisplay t) (inhibit-read-only t) (orig-offset (- (point-max) (cdr region))) (yas-prompt-functions '(yas-no-prompt))) (delete-region (car region) (cdr region)) (goto-char (car region)) (setcar region (point)) (insert region-contents) (setcdr region (point)) (if (and template (not (eq action ...))) (progn (unwind-protect (consult-yasnippet--expand-template template region region-contents) (unwind-protect ... ...)) (redisplay))))))(#s(yas--template :key "def" :content "(defun ${1:fun} (${2:args})\n  \"${3:docstring}\"\n  $..." :name "defun" :condition nil :expand-env nil :load-file "c:/Users/vadim/AppData/Roaming/.cache/emacs/straig..." :save-file nil :keybinding nil :uuid "defun" :menu-binding-pair ((menu-item "defun" (lambda nil (interactive) (yas--expand-or-visit-from-menu 'emacs-lisp-mode "defun")) :keys "def =>")) :group nil :perm-group nil :table #s(yas--table :name "emacs-lisp-mode" :hash #<hash-table equal 112/145 0x4cc9f973ad> :uuidhash #<hash-table equal 116/145 0x4cc9f97451> :parents nil :direct-keymap (keymap))) t)
>   #f(compiled-function () #<bytecode 0x21d31bdbbc63f52>)()
>   consult--with-preview-1(any (closure ((region-contents . "") (region 146 . 146) (buf . #<buffer *scratch*>) t) (action template) (save-current-buffer (set-buffer buf) (let ((yas-verbosity 0) (inhibit-redisplay t) (inhibit-read-only t) (orig-offset (- (point-max) (cdr region))) (yas-prompt-functions '(yas-no-prompt))) (delete-region (car region) (cdr region)) (goto-char (car region)) (setcar region (point)) (insert region-contents) (setcdr region (point)) (if (and template (not (eq action ...))) (progn (unwind-protect (consult-yasnippet--expand-template template region region-contents) (unwind-protect ... ...)) (redisplay)))))) #f(compiled-function (input cand) #<bytecode 0x507cd8d83ae1ec3>) #f(compiled-function (&rest args2) #<bytecode 0x9b4c737f7064cc6>) #f(compiled-function () #<bytecode 0x898af9c2985b7e4>))
>   consult--read-1((... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) :prompt "Choose a snipp..." :annotate (closure ... ... ...) :lookup consult--lookup-cdr :require-match t :state (closure ... ... ...) :category yasnippet :prompt ...)
>   apply(consult--read-1 (... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (:prompt "Choose a snipp..." :annotate ... :lookup consult--lookup-cdr :require-match t :state ... :category yasnippet :prompt "Select: " ...))
>   consult--read((... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) :prompt "Choose a snipp..." :annotate (closure ... ... ...) :lookup consult--lookup-cdr :require-match t :state (closure ... ... ...) :category yasnippet)
>   (let* ((buffer-undo-list t) (candidates (consult-yasnippet--candidates (if all-templates (yas--all-templates (map-values yas--tables)) (yas--all-templates (yas--get-snippet-tables)))))) (consult--read candidates :prompt "Choose a snippet: " :annotate (consult-yasnippet--annotate candidates) :lookup 'consult--lookup-cdr :require-match t :state (consult-yasnippet--preview) :category 'yasnippet))
>   consult-yasnippet--read-template(nil)
>   (and t (consult-yasnippet--read-template arg))
>   (let* ((template (and t (consult-yasnippet--read-template arg)))) (if template (yas-expand-snippet (progn (or (progn (and (memq ... cl-struct-yas--template-tags) t)) (signal 'wrong-type-argument (list 'yas--template template))) (aref template 2)) nil nil (progn (or (progn (and (memq ... cl-struct-yas--template-tags) t)) (signal 'wrong-type-argument (list 'yas--template template))) (aref template 5))) nil))
>   consult-yasnippet(nil)
>   funcall-interactively(consult-yasnippet nil)
>   command-execute(consult-yasnippet)

**Comment by d9d6ka** [comment]
Well, today I've tested my config at my work PC (previously I've tested it on my home PC).
Everything works as expected :man_shrugging:
All versions of emacs, yasnippet, consult-yasnippet are the same.

So, I will seek for problems on my home PC.

Sorry for wasting your time...
